# Image of workspace. Learn more: https://www.gitpod.io/docs/configure/workspaces/workspace-image
image: gitpod/workspace-full:latest

# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: startup
    before: |
      sudo apt update
      sudo apt upgrade --yes
      npm install npm@latest --global
      npm install @salesforce/cli --global
    init: |
      if [ ! -d $ssldir ]
      then
        echo "Pausing for 60 seconds..."
        sleep 60
        mkdir $ssldir
        cd $ssldir
        openssl genrsa -des3 -passout pass:$sslpwd -out server.pass.key
        openssl rsa -passin pass:$sslpwd -in server.pass.key -out server.key
        openssl req -new -key server.key -out server.csr
        openssl x509 -req -sha256 -days 365 -in server.csr -signkey server.key -out server.crt
        ls -la
        cd ..
      fi
    command: |
      cd $ssldir
      sf auth:jwt:grant --jwt-key-file $jwtkeyfile --client-id $devhub_clientid --username $devhub_username --alias $devhub_alias --instance-url=$devhub_url --set-default-dev-hub
      cd $workdir
      echo
      echo sf org list --all
      echo
      sf org list --all
      echo
      java --version | grep "Runtime"
      sf --version
      echo
      echo sf config:set target-dev-hub=\$devhub_alias
      echo
      sf config:set target-dev-hub=$devhub_alias
      sf org:open --url-only

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: Frontend
    description: Port 3000 for the frontend
    port: 3000
    onOpen: open-preview

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstar
