public class Case_Trigger_Recursion {

    public static Boolean BEFORE_INSERT_ALREADY_INVOKED = false;
    public static Boolean BEFORE_UPDATE_ALREADY_INVOKED = false;
    public static Boolean BEFORE_DELETE_ALREADY_INVOKED = false;

    public static Boolean AFTER_INSERT_ALREADY_INVOKED = false;
    public static Boolean AFTER_UPDATE_ALREADY_INVOKED = false;
    public static Boolean AFTER_DELETE_ALREADY_INVOKED = false;

    public static Boolean AFTER_UNDELETE_ALREADY_INVOKED = false;
}